name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔥 Auto URL generate
      - name: Set Website URL
        run: |
          echo "SITE_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_ENV

      # 🔥 Inject URL
      - name: Inject URL
        run: |
          sed -i "s|LOAD_URL|$SITE_URL|g" android/app/src/main/java/com/star/app/MainActivity.java

      # ✅ Java setup
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ✅ Android SDK setup (IMPORTANT 🔥)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Gradle setup (FIXED)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 🔥 Build APK
      - name: Build APK
        run: |
          cd android
          gradle assembleDebug

      # 📦 Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk