name: Build Signed APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # URL auto set
      - name: Set Website URL
        run: |
          echo "SITE_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_ENV

      # Inject URL
      - name: Inject URL
        run: |
          sed -i "s|LOAD_URL|$SITE_URL|g" android/app/src/main/java/com/star/app/MainActivity.java

      # Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Gradle 7.5
      - name: Setup Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip

      # 🔐 Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > my-release-key.jks

      # 🔐 Build Signed APK
      - name: Build Signed APK
        run: |
          cd android
          ../gradle-7.5/bin/gradle assembleRelease \
          -Pandroid.injected.signing.store.file=../my-release-key.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk